-- Nocturnal Games backend is provisioned in the dedicated Supabase project:
-- project: babybat-game-hub
-- ref: mbxevizxcwmmldjtbksq
--
-- Production migrations include the v3 hub layer plus v3.1 private Counsel:
--   organization_status
--   app_settings
--   mail_messages
--   evidence_submissions
--   notification_events
--   counsel_threads
--   counsel_messages
--   user_notification_preferences (includes per-account counsel_enabled preference)
--   push_subscriptions
--   push_server_config (server-only VAPID keypair)
--   private game-evidence Storage bucket + RLS
--   babybat-counsel Supabase Edge Function (JWT required)
--   babybat-ai-usage Supabase Edge Function (JWT required)
--   nocturnal-push Supabase Edge Function (JWT required)
--   Legacy/internal bridge RPCs: babybat_snapshot(), babybat_send_mail(), babybat_set_status()
--
-- Counsel RLS:
--   - each authenticated user can see only their own counsel_thread/messages
--   - thread entity_id must match that user's game membership
--   - Moxie preview from Shawn Site Admin cannot expose Moxie's Counsel
--
-- Counsel app settings:
--   counsel_enabled
--   counsel_model
--   counsel_reasoning_effort
--   sovereign_counsel_notes
--   nocturne_counsel_notes
--
-- OpenAI API key is NOT stored in SQL. It belongs only in the Supabase
-- Edge Function secret named OPENAI_API_KEY.
--
-- Push delivery notes:
--   - notification_events retains legacy transport fields for migration safety; v3.2.3 uses push only.
--   - users manage push preferences through RLS; deprecated transport columns are not used by v3.2.3.
--   - push endpoint/keys are registered through the authenticated Edge Function.
--   - push_server_config is not readable by anon/authenticated clients; only the
--     public VAPID key is returned by nocturnal-push.
--
-- Earlier core tables remain in production:
-- profiles, game_entities, games, game_memberships, directives, scoring_rules,
-- point_transactions, reward_tiers, rewards, rulebook_sections,
-- access_claims, organization_members, one-time access claims, RLS policies,
-- and automatic reward unlocking.
--
-- The old fake/local chat tables remain removed.
--
-- This file is documentation-only so a static Vercel deploy cannot accidentally
-- create duplicate/outdated schema in the wrong Supabase project.

-- v3.2.3 multi-game production notes:
--   - Added infernal-firm-game as an independent game record with Nocturne as GM.
--   - Shawn retains site-admin membership for maintenance/QA; Moxie is game_master.
--   - Vex is attached only when he claims the dedicated one-time Infernal player code.
--   - Infernal score baseline is 434 from the uploaded controlled master ledger;
--     unresolved Request #1-#13 details remain summarized rather than fabricated.
--   - Mail categories now include 'request' in addition to the existing 'directive'.
--   - Push endpoint uniqueness is scoped to (user_id, game_id, endpoint), allowing
--     one installed PWA/device subscription to participate in multiple games.
--   - nocturnal-push v2 registers an enabled device across all current game memberships
--     while each notification event remains game-scoped.
--   - Infernal Counsel is disabled by default until a dedicated private Counsel model exists.
